# Generated by Django 5.0.6 on 2024-06-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_account_balance_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='account_balance',
        ),
    ]
