# Generated by Django 5.0.6 on 2024-07-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
